### ISSUE TITLE
[bug]反常理的密闭容器消耗

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [NotAlwaysTrue/CBRN_Expansion#38]
bug描述 在合成台为空的撒布(手)榴弹 装填化学药剂时 会将装填药剂的密封完全消耗 而不是只剩下0%的空容器
复现方式 打开合成台 使用任意装填50%药剂的密封容器为空的撒布手榴弹装填药剂 合成完后密封容器完全消失

**Comment by NotAlwaysTrue** [comment]
这不算是个bug, 当初设计的时候本来打算用更好的合成配方替代目前的配方, 但是因为产能原因就搁置了
因此使用消耗容器的方式增加一点总成本
在以后的更新会用更好的方式替换现有的
