### ISSUE TITLE
[bug]核弹头引爆倒计时无法改变

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [NotAlwaysTrue/CBRN_Expansion#40]
bug描述: 核弹头倒计时会在使用按钮减少到20%后无法更改
复现方式: 手持中子弹头 点击减少10秒直到弹头耐久达到20% 之后点击增加/减少倒计时按钮均无法改变倒计时时间 
勾选启动引爆序列后倒计时会正常减少 且减少的倒计时无法再次使用增加按钮恢复

**Comment by NotAlwaysTrue** [comment]
减少至20无法再减少倒计时时长是物品设计 20秒后所有弹头为不可终止倒计时
20秒时无法增加是bug
