### ISSUE TITLE
弹匣tags变更

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [NotAlwaysTrue/CBRN_Expansion#43]
前置mod九州武库的6.8*51弹夹改成了6.8*43 且tag也进行了更改 此mod的6.8弹夹塞不进去了

你mod
`<Item identifier="lm_68_51_mag_rev" subcategory="tsm_modifiedmagazines" scale="0.23" category="weapon" maxstacksize="6" cargocontaineridentifier="tsm_hazardous_container" linkable="true" tags="lm_magazine,smallitem,lm_gjzd,68_51mag,magazine,rev_mag" impactsoundtag="impact_metal_light" health="30">`

前置
`<Item name="联盟6.8普通弹匣" identifier="lm_68_51_magazine" subcategory="tsm_coalition" scale="0.23" category="weapon" maxstacksize="6" cargocontaineridentifier="tsm_metalcrate" linkable="true" tags="lm_magazine,smallitem,lm_cjzd,68_43mag,magazine" impactsoundtag="impact_metal_light" health="30">`

**Comment by NotAlwaysTrue** [comment]
已和九州武库作者确认 他在很久以前已经把6.8*43改回6.8*51了

**Comment by NotAlwaysTrue** [comment]
如果更新后你的本地文件还是6.8*43的话你可能需要取消订阅再重新订阅才行
