### ISSUE TITLE
前哨站任务敌人装备id问题

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [NotAlwaysTrue/CBRN_Expansion#48]
清剿CBRN小队任务中敌人的弹夹id已更新 而mod中使用的id没变
<img width="446" alt="Barotrauma_J0a2kkyNUa" src="https://github.com/user-attachments/assets/d4688556-ab1e-4b4a-a290-f0a514f938f8" />

**Comment by NotAlwaysTrue** [comment]
已知，正在一步一步修复，九州的本次更新动的东西太多了修不过来T_T
